- name: Include creation variables
  include_vars:
    file: ../../cloud_create/defaults/main.yaml

- name: Delete DNS records
  vars:
    type: '{{ name|ht_type }}'
    id: '{{ name|ht_id }}'
  include_tasks: dns.yaml
  loop: '{{ groups.all }}'
  loop_control:
    loop_var: name
  tags:
    - dns

- name: Get server info from Scaleway
  scaleway_server_info:
    region: '{{ cloud_params.scaleway.region }}'
  register: scw_servers
  tags:
    - scaleway

- name: Destroy nodes
  include_tasks: destroy_each.yaml
  loop:
    - scaleway
    - hcloud
    - vultr
  loop_control:
    loop_var: provider
