- name: Destroy Scaleway {{ type }} {{ id }}
  scaleway_compute:
    name: '{{ name }}'
    organization: '{{ scaleway.organization }}'
    commercial_type: '{{ cloud_params.scaleway.sizes[type] }}'
    image: '{{ cloud_params.scaleway.image }}'
    region: '{{ cloud_params.scaleway.region }}'
    state: absent
    wait: yes
  tags:
    - scaleway

- name: Delete Scaleway volume {{ vol_id }} for {{ type }} {{ id }}
  vars:
    query: 'scaleway_server_info[?hostname==`{{ name }}`].volumes."0".id | [0]'
    vol_id: '{{ scw_servers | json_query(query) }}'
  scw_del_vol_id:
    id: '{{ vol_id }}'
    region: '{{ cloud_params.scaleway.region }}'
  tags:
    - scaleway
