- name: Add GlusterFS PPA
  apt_repository:
    repo: '{{ gluster_params.ppa }}'
    update_cache: yes
    state: present
- name: Install GlusterFS
  apt:
    name: glusterfs-server
    update_cache: no
    state: latest

- name: Establish GlusterFS storage pool
  gluster_peer:
    nodes: '{{ groups.managers | difference([inventory_hostname]) }}'
    state: present
  run_once: yes

- name: Create GlusterFS brick directory
  file:
    path: '/data/{{ gluster_params.volume.brick }}'
    state: directory
- name: Create shared Docker volumes disk image
  vars:
    image: '/data/{{ gluster_params.volume.name }}.img'
  command:
    cmd: 'truncate -s {{ gluster_params.volume.size }} {{ image }}'
    creates: "{{ image }}"
- name: Format shared Docker volumes disk image
  filesystem:
    dev: '/data/{{ gluster_params.volume.name }}.img'
    fstype: xfs

- name: Mount and add shared Docker volumes disk image to /etc/fstab
  mount:
    src: '/data/{{ gluster_params.volume.name }}.img'
    path: '/data/{{ gluster_params.volume.brick }}'
    fstype: xfs
    state: mounted
- name: Create volume directory on mounted brick
  file:
    path: '/data/{{ gluster_params.volume.brick }}/{{ gluster_params.volume.name }}'
    mode: u=rwx,g=rx
    state: directory

- name: Create and start GlusterFS volume
  gluster_volume:
    name: '{{ gluster_params.volume.name }}'
    replicas: '{{ groups.managers | length }}'
    bricks: '/data/{{ gluster_params.volume.brick }}/{{ gluster_params.volume.name }}'
    cluster: '{{ groups.managers }}'
    transport: tcp
    state: present
  run_once: yes
- name: Mount and add shared Docker volumes GlusterFS to /etc/fstab
  mount:
    src: '{{ inventory_hostname }}:/{{ gluster_params.volume.name }}'
    path: '{{ gluster_params.volume.mountpoint }}'
    fstype: glusterfs
    opts: defaults,_netdev,noauto,x-systemd.automount
    state: mounted
