- name: Initialize Docker Swarm
  docker_swarm:
    advertise_addr: '{{ wireguard.interface }}'
    listen_addr: '{{ wireguard.interface }}'
    state: present
  register: sw_init_result
  when: inventory_hostname == init_node
- name: Copy manager join token to other nodes
  set_fact:
    sw_manager_token: '{{ sw_init_result.swarm_facts.JoinTokens.Manager }}'
  delegate_to: '{{ item }}'
  delegate_facts: yes
  loop: '{{ other_nodes }}'
  when: inventory_hostname == init_node
- name: Copy worker join token to controller
  set_fact:
    sw_worker_token: '{{ sw_init_result.swarm_facts.JoinTokens.Worker }}'
  delegate_to: localhost
  delegate_facts: yes
  when: inventory_hostname == init_node

- name: Join other managers to Docker Swarm
  docker_swarm:
    advertise_addr: '{{ wireguard.interface }}'
    listen_addr: '{{ wireguard.interface }}'
    remote_addrs:
      - '{{ init_node }}'
    join_token: '{{ sw_manager_token }}'
    state: join
  when: inventory_hostname != init_node

- name: Create Traefik network
  docker_network:
    name: '{{ swarm.traefik_network.name }}'
    driver: overlay
    ipam_config:
      - subnet: '{{ swarm.traefik_network.subnet }}'
    state: present
  when: inventory_hostname == init_node
- name: Upload Docker secrets
  docker_secret:
    name: '{{ item.key }}'
    data: '{{ item.value.value }}'
    data_is_b64: "{{ item.value.b64 | default('no') }}"
    state: present
  loop: '{{ docker_secrets | dict2items }}'
  loop_control:
    label: '{{ item.key }}'
  run_once: yes
- name: Save Docker registry to environment
  vars:
    var: DOCKER_REGISTRY
    value: '{{ docker.registry }}'
  import_tasks: env.yaml
- name: Log in to Docker registry
  docker_login:
    username: nologin
    password: '{{ scaleway_token }}'
    registry_url: '{{ docker.registry }}'
    state: present
- name: Save shared Docker volume path to environment
  vars:
    var: DOCKER_SHARED
    value: '{{ gluster_params.volume.mountpoint }}'
  import_tasks: env.yaml
- name: Create shared Docker volume directories
  file:
    path: '{{ gluster_params.volume.mountpoint }}/{{ item }}'
    mode: u=rwx
    state: directory
  loop: '{{ swarm.shared_volumes }}'
  run_once: yes
- name: Synchronize Docker stacks
  synchronize:
    src: ../stacks
    dest: '{{ gluster_params.volume.mountpoint }}/'
    archive: no
    recursive: yes
    links: yes
    times: yes
    delete: yes
  run_once: yes
