gluster_params:
  ppa: ppa:gluster/glusterfs-7
  volume:
    name: docker-shared-volumes
    brick: brick0
    size: 8G
    fs: xfs
    mountpoint: /mnt/docker-shared
swarm:
  traefik_network:
    name: traefik
    subnet: 10.137.0.0/16
  shared_volumes:
    - portainer
    - ctfd/mariadb
    - ctfd/uploads
    - chad_pki
