gluster_params:
  ppa: ppa:gluster/glusterfs-7
  volume:
    name: docker-shared-volumes
    brick: brick0
    size: 8G
    fs: xfs
    mountpoint: /mnt/docker-shared
swarm:
  traefik_network: traefik
  shared_volumes:
    - portainer
