ubuntu_utils:
  - python3-pip
  - iputils-ping
  - traceroute
  - ldnsutils
wireguard:
  ppa: ppa:wireguard/wireguard
  dir: /etc/wireguard
  privkey_file: privkey
  interface: priv-mesh
  port: 51820
  cidr: 23
  ip_prefix:
    manager: '192.168.68'
    worker: '192.168.69'
docker:
  ubuntu:
    gpg: https://download.docker.com/linux/ubuntu/gpg
    repo: https://download.docker.com/linux/ubuntu
  registry: rg.fr-par.scw.cloud/ht20
  volumes:
    image: /data/docker-volumes.img
    mountpoint: /var/lib/docker/volumes
    size: 8G
