ubuntu_utils:
  - python3-pip
  - iputils-ping
  - traceroute
  - ldnsutils
  - tree
wireguard:
  ppa: ppa:wireguard/wireguard
  dir: /etc/wireguard
  privkey_file: privkey
  interface: priv-mesh
  keepalive: 5
  port: 51820
  cidr: 23
  ip_prefix:
    manager: '192.168.68'
    worker: '192.168.69'
docker:
  ubuntu:
    gpg: https://download.docker.com/linux/ubuntu/gpg
    repo: https://download.docker.com/linux/ubuntu
  registry: rg.fr-par.scw.cloud/ht20
  storage:
    image: /data/docker.img
    mountpoint: /var/lib/docker
    size: 128G
timezone: Europe/Dublin
