- name: Create disk image directory
  file:
    path: '{{ docker.storage.image | dirname }}'
    mode: u=rwx,g=rx
    state: directory
- name: Create Docker state disk image
  command:
    cmd: 'truncate -s {{ docker.storage.size }} {{ docker.storage.image }}'
    creates: '{{ docker.storage.image }}'
- name: Format Docker state disk image as XFS
  filesystem:
    dev: '{{ docker.storage.image }}'
    fstype: xfs

- name: Mount and add Docker state disk image to /etc/fstab
  mount:
    src: '{{ docker.storage.image }}'
    path: '{{ docker.storage.mountpoint }}'
    fstype: xfs
    opts: defaults,pquota
    state: mounted

- name: Add Docker GPG key
  apt_key:
    url: '{{ docker.ubuntu.gpg }}'
    state: present
  tags:
    - gpg
- name: Add Docker APT repository
  apt_repository:
    repo: 'deb [arch=amd64] {{ docker.ubuntu.repo }} {{ ansible_lsb.codename }} stable'
    update_cache: yes
    state: present
- name: Install Docker
  apt:
    name:
      # FUCK MY LIFE https://github.com/moby/moby/issues/40626
      - docker-ce=5:19.03.6~3-0~ubuntu-bionic
      - docker-ce-cli=5:19.03.6~3-0~ubuntu-bionic
      - containerd.io
    force: yes
    update_cache: no
    state: present
- name: Hold Docker version
  command: apt-mark hold docker-ce docker-ce-cli
- name: Install Docker SDK for Python
  pip:
    name: docker
    state: latest

- name: Install runc-hack
  copy:
    src: runc-hack
    dest: /usr/local/bin/runc-hack
    mode: +x
- name: Copy Docker daemon config
  copy:
    src: docker_daemon.json
    dest: /etc/docker/daemon.json
  notify: Restart Docker

- name: Check if WeaveWorks plugin is installed
  command: docker plugin inspect {{ docker.weaveworks }}
  ignore_errors: yes
  register: ww_result
- name: Install WeaveWorks network plugin
  command: docker plugin install --grant-all-permissions {{ docker.weaveworks }}
  when: ww_result.failed
- name: Temporarily disable WeaveWorks network plugin
  command: docker plugin disable {{ docker.weaveworks }}
  when: ww_result.failed
- name: Enable WeaveWorks network plugin multicast
  command: docker plugin set {{ docker.weaveworks }} WEAVE_MULTICAST=1
  when: ww_result.failed
- name: Re-enable WeaveWorks network plugin
  command: docker plugin enable {{ docker.weaveworks }}
  when: ww_result.failed
