- name: Update system
  import_tasks: update.yaml

- name: Install utilities
  apt:
    name: '{{ ubuntu_utils }}'
    state: latest

- name: Add all nodes to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^.*{{ item }}$'
    line: '{{ hostvars[item].ansible_host }}	{{ item }}'
    state: present
  when: hostvars[item].ansible_host is defined
  loop: '{{ groups.all }}'

- name: Set up Docker
  import_tasks: docker.yaml
