- name: Update system
  import_tasks: update.yaml
  tags:
    - update

- name: Install utilities
  apt:
    name: '{{ ubuntu_utils }}'
    state: latest

- name: Set up timezone
  timezone:
    name: '{{ timezone }}'

- name: Set up firewall
  import_tasks: firewall.yaml
  tags:
    - firewall

- name: Set up WireGuard
  import_tasks: wireguard.yaml
  tags:
    - wireguard

- name: Add all nodes to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^.*{{ item }}$'
    line: '{{ wireguard.ip_prefix[hostvars[item].ht_node.type] }}.{{ hostvars[item].ht_node.id + 1 }}	{{ item }}'
    state: present
  loop: '{{ groups.all }}'

- name: Set up Docker
  import_tasks: docker.yaml
  tags:
    - docker
