version: '3.3'
services:
  db:
    image: mariadb:10
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --wait_timeout=28800
    environment:
      - MYSQL_INITDB_SKIP_TZINFO=yes
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/ctfd_db_root_password
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD_FILE=/run/secrets/ctfd_db_password
      - MYSQL_DATABASE=ctfd
    volumes:
      - $DOCKER_SHARED/ctfd/mariadb:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      # https://github.com/moby/moby/issues/37822
      endpoint_mode: dnsrr
    secrets:
      - ctfd_db_root_password
      - ctfd_db_password
  redis:
    image: redis:alpine
    deploy:
      mode: replicated
      replicas: 1

  chad:
    image: $DOCKER_REGISTRY/chad/server
    environment:
      - DOCKER_REGISTRY=$DOCKER_REGISTRY
      - ID_SALT_FILE=/run/secrets/chad_id_salt
      - FLAG_PREFIX=HackTrinity
      - REDIS_URL=redis://redis/1
      - GATEWAY_IMAGE=$DOCKER_REGISTRY/chad/gateway
      - GATEWAY_DOMAIN=chad-gw.sys.hacktrinity.org
      - TRAEFIK_NETWORK=traefik
      #- CLEANUP_DISABLED=yes
      - CLEANUP_INTERVAL=300
      - CLEANUP_INSTANCE_TIMEOUT=600
      - CLEANUP_GATEWAY_TIMEOUT=1200
    volumes:
      - /var/run/docker.sock:/run/docker.sock
      - /root/.docker/config.json:/root/.docker/config.json:ro
      - $DOCKER_SHARED/chad_pki:/etc/chad_pki
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    secrets:
      - chad_id_salt

  app:
    image: $DOCKER_REGISTRY/ctfd
    environment:
      - SECRET_KEY_FILE=/run/secrets/ctfd_secret_key
      - DATABASE_PASSWORD_FILE=/run/secrets/ctfd_db_password
      - DATABASE_URL=mysql+pymysql://ctfd:{password}@db/ctfd
      - REDIS_URL=redis://redis/0

      - MAILFROM_ADDR=ctfd@hacktrinity.org
      - MAIL_SERVER=mail.nul.ie
      - MAIL_PORT=587
      - MAIL_USEAUTH=True
      - MAIL_USERNAME=admin@hacktrinity.org
      - MAIL_PASSWORD_FILE=/run/secrets/ctfd_smtp_password
      - MAIL_TLS=True

      - LOG_FOLDER=/var/log/CTFd
      - UPLOAD_FOLDER=/var/lib/uploads

      - REVERSE_PROXY=True
      - TEMPLATES_AUTO_RELOAD=False
      - UPDATE_CHECK=False

      - CHAD_ENDPOINT=http://chad
      - >-
        MAIL_LABELS={
          "tcd.ie":"TCD",
          "ucdconnect.ie":"UCD",
          "mytudublin.ie":"TU Dublin",
          "mydit.ie":"TU Dublin",
          "mail.dcu.ie":"DCU",
          "qub.ac.uk": "QUB",
          "umail.ucc.ie":"UCC"
        }
    volumes:
      - $DOCKER_SHARED/ctfd/uploads:/var/lib/uploads
      - logs:/var/log/CTFd
    networks:
      - default
      - traefik
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == manager
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.ctfd.rule=Host(`hacktrinity.org`)'
        - 'traefik.http.routers.ctfd.entrypoints=https'
        - 'traefik.http.routers.ctfd.tls=true'
        - 'traefik.http.routers.ctfd.tls.certresolver=le'
        - 'traefik.http.routers.ctfd.tls.domains[0].sans=*.hacktrinity.org,*.sys.hacktrinity.org,*.challs.hacktrinity.org'
        - 'traefik.http.services.ctfd.loadbalancer.server.port=8000'
    secrets:
      - ctfd_secret_key
      - ctfd_db_password
      - ctfd_smtp_password

volumes:
  logs:

networks:
  traefik:
    external: true

secrets:
  ctfd_db_root_password:
    external: true
  ctfd_db_password:
    external: true
  ctfd_secret_key:
    external: true
  ctfd_smtp_password:
    external: true
  chad_id_salt:
    external: true
