version: '3.2'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  app:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - /mnt/docker/portainer:/data
    networks:
      - agent
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.portainer.rule=Host(`portainer.sys.hacktrinity.org`)'
        - 'traefik.http.routers.portainer.entrypoints=https'
        - 'traefik.http.routers.portainer.tls=true'
        - 'traefik.http.routers.portainer.tls.certresolver=le'
        - 'traefik.http.services.portainer.loadbalancer.server.port=9000'

networks:
  agent:
    driver: overlay
  traefik-public:
    external: true
