version: '3.3'
services:
  app:
    image: nginx
    volumes:
      - /mnt/docker-shared/stacks/tmp:/usr/share/nginx/html:ro
    networks:
      - traefik
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.tmp.rule=Host(`hacktrinity.org`)'
        - 'traefik.http.routers.tmp.entrypoints=https'
        - 'traefik.http.routers.tmp.tls=true'
        - 'traefik.http.routers.tmp.tls.certresolver=le'
        - 'traefik.http.routers.tmp.tls.domains[0].sans=*.hacktrinity.org,*.sys.hacktrinity.org,*.challs.hacktrinity.org'
        - 'traefik.http.services.tmp.loadbalancer.server.port=80'

networks:
  traefik:
    external: true
