version: '3.3'
services:
  whoami:
    image: containous/whoami
    networks:
      - traefik
    deploy:
      mode: global
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.whoami.rule=Host(`whoami.sys.hacktrinity.org`)'
        - 'traefik.http.routers.whoami.entrypoints=https'
        - 'traefik.http.routers.whoami.tls=true'
        - 'traefik.http.routers.whoami.tls.certresolver=le'
        - 'traefik.http.routers.whoami.tls.domains[0].main=*.sys.hacktrinity.org'
        - 'traefik.http.routers.whoami.tls.domains[0].sans=hacktrinity.org,*.hacktrinity.org,*.challs.hacktrinity.org'
        - 'traefik.http.services.whoami.loadbalancer.server.port=80'
  app:
    image: traefik:2.1
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    command:
      - --providers.docker
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=traefik
      - --providers.docker.defaultRule=Host(`{{ .Name }}.hacktrinity.org`)
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
      - --certificatesResolvers.le.acme.email=jackos1998@gmail.com
      - --certificatesResolvers.le.acme.storage=/acme/cache.json
      - --certificatesResolvers.le.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.le.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --api.dashboard=true
      - --log.level=INFO
      - --accesslog=true
    environment:
      - CF_API_EMAIL=jackos1998@gmail.com
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cloudflare_dns_token
      - CF_ZONE_API_TOKEN_FILE=/run/secrets/cloudflare_zone_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/acme
    networks:
      - traefik
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      labels:
        - 'traefik.enable=true'
        # Middleware
        - 'traefik.http.middlewares.auth.basicauth.usersfile=/run/secrets/traefik_users'
        - 'traefik.http.middlewares.https-redirect.redirectscheme.scheme=https'
        - 'traefik.http.middlewares.https-redirect.redirectscheme.permanent=true'
        - 'traefik.http.middlewares.www-redirect.redirectregex.regex=^https://www.hacktrinity.org/(.*)'
        - 'traefik.http.middlewares.www-redirect.redirectregex.replacement=https://hacktrinity.org/$${1}'
        - 'traefik.http.middlewares.www-redirect.redirectregex.permanent=true'
        # Global HTTP -> HTTPS redirect
        - 'traefik.http.services.noop.loadbalancer.server.port=1234' # dummy value
        - 'traefik.http.routers.https-redirect.entrypoints=http'
        - 'traefik.http.routers.https-redirect.rule=HostRegexp(`{host:.+}`)'
        - 'traefik.http.routers.https-redirect.middlewares=https-redirect'
        - 'traefik.http.routers.https-redirect.service=noop'
        # www redirect
        - 'traefik.http.routers.www-redirect.rule=Host(`www.hacktrinity.org`)'
        - 'traefik.http.routers.www-redirect.entrypoints=https'
        - 'traefik.http.routers.www-redirect.tls=true'
        - 'traefik.http.routers.www-redirect.tls.certresolver=le'
        - 'traefik.http.routers.www-redirect.tls.domains[0].main=*.hacktrinity.org'
        - 'traefik.http.routers.www-redirect.tls.domains[0].sans=hacktrinity.org,*.hacktrinity.org,*.challs.hacktrinity.org'
        - 'traefik.http.routers.www-redirect.middlewares=www-redirect'
        - 'traefik.http.routers.www-redirect.service=noop'
        # Dashboard
        - 'traefik.http.routers.api.rule=Host(`traefik.sys.hacktrinity.org`)'
        - 'traefik.http.routers.api.entrypoints=https'
        - 'traefik.http.routers.api.tls=true'
        - 'traefik.http.routers.api.tls.certresolver=le'
        - 'traefik.http.routers.api.tls.domains[0].main=*.sys.hacktrinity.org'
        - 'traefik.http.routers.api.tls.domains[0].sans=hacktrinity.org,*.hacktrinity.org,*.challs.hacktrinity.org'
        - 'traefik.http.routers.api.service=api@internal'
        - 'traefik.http.routers.api.middlewares=auth'
    secrets:
      - cloudflare_dns_token
      - cloudflare_zone_token
      - traefik_users

volumes:
  acme:

networks:
  traefik:
    external: true

secrets:
  cloudflare_dns_token:
    external: true
  cloudflare_zone_token:
    external: true
  traefik_users:
    external: true
