- name: Create {{ type }} {{ i }} on Scaleway
  scaleway_compute:
    name: '{{ type }}{{ i }}'
    organization: '{{ scaleway.organization }}'
    commercial_type: '{{ cloud_params.scaleway.sizes[type] }}'
    image: '{{ cloud_params.scaleway.image }}'
    region: '{{ cloud_params.scaleway.region }}'
    public_ip: dynamic
    enable_ipv6: no
    state: running
    wait: true
    tags:
      - scaleway
      - hacktrinity
      - '{{ type }}s'
  tags:
    - scaleway
- name: Get {{ type }} {{ i }} info from Scaleway
  scaleway_server_info:
    region: '{{ cloud_params.scaleway.region }}'
  register: scw_result
  tags:
    - scaleway
- name: Create DNS records for {{ type }} {{ i }}
  import_tasks: dns.yaml
  vars:
    index: '{{ i }}'
    query: 'scaleway_server_info[?hostname==`{{ type }}{{ i }}`].public_ip.address | [0]'
    ip: "{{ scw_result | json_query(query) }}"
  tags:
    - dns
    - scaleway

- name: Create {{ type }} {{ i + 1 }} on Hetzner Cloud
  vars:
    labels:
      # Dictionary keys don't use templating...
      - key: '{{ type }}s'
        value: ''
  hcloud_server:
    name: '{{ type }}{{ i + 1 }}'
    server_type: '{{ cloud_params.hcloud.sizes[type] }}'
    image: '{{ cloud_params.hcloud.image }}'
    location: '{{ cloud_params.hcloud.region }}'
    ssh_keys:
      - '{{ cloud_params.hcloud.ssh_key }}'
    state: started
    labels: '{{ labels|items2dict }}'
  register: hcloud_result
  tags:
    - hcloud
- name: Create DNS records for {{ type }} {{ i + 1 }}
  import_tasks: dns.yaml
  vars:
    index: '{{ i + 1 }}'
    ip: '{{ hcloud_result.hcloud_server.ipv4_address }}'
  tags:
    - dns
    - hcloud
- name: Create reverse DNS records for {{ type }} {{ i + 1 }}
  hcloud_rdns:
    server: '{{ type }}{{ i + 1 }}'
    ip_address: '{{ hcloud_result.hcloud_server.ipv4_address }}'
    dns_ptr: '{{ i + 1 }}.{{ type }}s.sys.{{ domain }}'
    state: present
  tags:
    - dns
    - hcloud

- name: Create {{ type }} {{ i + 2 }} on Vultr
  vultr_server:
    name: '{{ type }}{{ i + 2 }}'
    hostname: '{{ type }}{{ i + 2 }}'
    plan: '{{ cloud_params.vultr.sizes[type] }}'
    os: '{{ cloud_params.vultr.image }}'
    region: '{{ cloud_params.vultr.region }}'
    ssh_keys:
      - '{{ cloud_params.vultr.ssh_key }}'
    ipv6_enabled: no
    state: started
    tag: '{{ type }}s'
  register: vultr_result
  tags:
    - vultr
- name: Create DNS records for {{ type }} {{ i + 2 }}
  import_tasks: dns.yaml
  vars:
    index: '{{ i + 2 }}'
    ip: '{{ vultr_result.vultr_server.v4_main_ip }}'
  tags:
    - dns
    - vultr
