- name: Create {{ type }} {{ i }} on Hetzner Cloud
  vars:
    labels:
      # Dictionary keys don't use templating...
      - key: '{{ type }}s'
        value: ''
  hcloud_server:
    name: '{{ type }}{{ i }}'
    server_type: '{{ cloud_params.hcloud.sizes[type] }}'
    image: '{{ cloud_params.hcloud.image }}'
    location: '{{ cloud_params.hcloud.region }}'
    ssh_keys:
      - '{{ cloud_params.hcloud.ssh_key }}'
    state: started
    labels: '{{ labels|items2dict }}'
  register: hcloud_result
  tags:
    - hcloud
- name: Create DNS records for {{ type }} {{ i }}
  import_tasks: dns.yaml
  vars:
    index: '{{ i }}'
    ip: '{{ hcloud_result.hcloud_server.ipv4_address }}'
  tags:
    - dns
    - hcloud
- name: Create reverse DNS entry for {{ ip }} -> {{ record }}
  vars:
    ip: '{{ hcloud_result.hcloud_server.ipv4_address }}'
    record: '{{ i }}.{{ type }}s.sys.{{ domain }}'
  hcloud_rdns:
    server: '{{ type }}{{ i }}'
    ip_address: '{{ ip }}'
    dns_ptr: '{{ record }}'
    state: present
  tags:
    - dns
    - hcloud
