- name: Create {{ type }} {{ i }} on Scaleway
  scaleway_compute:
    name: '{{ type }}{{ i }}'
    organization: "{{ scaleway['organization'] }}"
    commercial_type: "{{ params['scaleway']['sizes'][type] }}"
    image: "{{ params['scaleway']['image'] }}"
    region: "{{ params['scaleway']['region'] }}"
    public_ip: dynamic
    enable_ipv6: no
    state: running
    wait: true
    tags:
      - scaleway
      - hacktrinity
      - '{{ type }}s'
- name: Get {{ type }} {{ i }} info from Scaleway
  scaleway_server_info:
    region: "{{ params['scaleway']['region'] }}"
  register: scw_result
- name: Create DNS records for {{ type }} {{ i }}
  import_tasks: dns.yaml
  vars:
    index: '{{ i }}'
    query: 'scaleway_server_info[?hostname==`{{ type }}{{ i }}`].public_ip.address | [0]'
    ip: "{{ scw_result | json_query(query) }}"

- name: Create {{ type }} {{ i + 1 }} on Hetzner Cloud
  vars:
    labels:
      # Dictionary keys don't use templating...
      - key: '{{ type }}s'
        value: ''
  hcloud_server:
    name: '{{ type }}{{ i + 1 }}'
    server_type: "{{ params['hcloud']['sizes'][type] }}"
    image: "{{ params['hcloud']['image'] }}"
    location: "{{ params['hcloud']['region'] }}"
    ssh_keys:
      - "{{ params['hcloud']['ssh_key'] }}"
    state: started
    labels: '{{ labels|items2dict }}'
  register: hcloud_result
- name: Create DNS records for {{ type }} {{ i + 1 }}
  import_tasks: dns.yaml
  vars:
    index: '{{ i + 1 }}'
    ip: "{{ hcloud_result['hcloud_server']['ipv4_address'] }}"

- name: Create {{ type }} {{ i + 2 }} on Vultr
  vultr_server:
    name: '{{ type }}{{ i + 2 }}'
    plan: "{{ params['vultr']['sizes'][type] }}"
    os: "{{ params['vultr']['image'] }}"
    region: "{{ params['vultr']['region'] }}"
    ssh_keys:
      - "{{ params['vultr']['ssh_key'] }}"
    ipv6_enabled: no
    state: started
    tag: '{{ type }}s'
  register: vultr_result
- name: Create DNS records for {{ type }} {{ i + 2 }}
  import_tasks: dns.yaml
  vars:
    index: '{{ i + 2 }}'
    ip: "{{ vultr_result['vultr_server']['v4_main_ip'] }}"
