- name: Add SSH keys
  import_tasks: ssh_keys.yaml
  tags:
    - ssh_keys

- name: Create managers
  import_tasks: create.yaml
  vars:
    type: manager
- name: Create workers
  import_tasks: create.yaml
  vars:
    type: worker

- name: Reload inventory
  meta: refresh_inventory
