- name: Restart WireGuard
  systemd:
    unit: 'wg-quick@{{ wireguard.interface }}.service'
    state: restarted
  when: not wg_started.changed

- name: Reload iptables
  command: netfilter-persistent reload
  when: not iptables_started.changed

- name: Restart Docker
  systemd:
    unit: docker.service
    state: restarted
