- hosts: all
  gather_facts: no
  tasks:
    - name: Wait for nodes to come online
      wait_for_connection:
        timeout: 120
    - name: Gather facts
      setup:
    - import_role:
        name: common_setup

- hosts: managers
  vars:
    init_node: manager0
    others: '{{ groups.managers | difference([init_node]) }}'
  roles:
    - manager_setup
